config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :sessions, controllers: {
    sessions: "users/sessions"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :projects, only: %i[index new create show] do
    scope module: :projects do
      resources :status_changes, only: %i[new create]
      resources :comments, only: %i[new create]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Entryable

  validates :text, presence: true

  def to_s
    text
  end
end

app/models/concerns/entryable.rb
module Entryable
  extend ActiveSupport::Concern

  included do
    has_one :entry, as: :entryable, touch: true, dependent: :destroy
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :project
  belongs_to :user

  delegated_type :entryable, types: %w[Comment ProjectStatusChange]

  broadcasts_to ->(entry) { [entry.project, "entries"] }, inserts_by: :append, partial: "projects/entry"
end

app/models/project.rb
class Project < ApplicationRecord
  enum :status, to_do: 0, in_progress: 1, blocked: 2, done: 3

  validates :name, :text, :status, presence: true

  has_many :entries, dependent: :destroy

  def to_s
    name
  end
end

app/models/project_status_change.rb
class ProjectStatusChange < ApplicationRecord
  include Entryable
end

app/models/project_status_change/creator.rb
class ProjectStatusChange::Creator
  include ActiveModel::Model

  attr_accessor :project, :user, :status

  def perform
    project.transaction do
      project_status = ProjectStatusChange.new(from: project.status, to: status)
      Entry.create!(project: project, user: user, entryable: project_status)
      project.update!(status: status)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!
end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @comment = Comment.new
  end

  def create
    @project = Project.find(params[:project_id])
    @comment = Comment.new(comment_params)

    if @comment.valid?
      Entry.create!(project: @project, user: current_user, entryable: @comment)
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.expect(comment: %i[text])
  end
end

app/controllers/projects/status_changes_controller.rb
class Projects::StatusChangesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
  end

  def create
    project = Project.find(params[:project_id])

    ProjectStatusChange::Creator.new(
      status: params[:status],
      project: project,
      user: current_user
    ).perform
    redirect_to project_path(project)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @entries = @project.entries.includes(:user, :entryable).order(created_at: :asc)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.expect(project: %i[name text status])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "authentication"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def error_on(object, field)
    errors = object.errors.messages[field.to_sym]
    return if errors.blank?

    content_tag(
      :div,
      error_text(errors),
      class: "alert alert-danger px-3 py-2 my-2"
    )
  end

  private

  def error_text(errors)
    errors.first.upcase_first
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def project_statuses
    Project.statuses.map do |status, _value|
      [t(status, scope: "activerecord.attributes.project.statuses"), status]
    end
  end

  def project_status_badge(project)
    {
      to_do: "text-bg-secondary",
      in_progress: "text-bg-primary",
      blocked: "text-bg-danger",
      done: "text-bg-success"
    }.fetch(project.status.to_sym)
  end
end

app/views/layouts/_flash.html.slim
- if notice
  .alert.alert-success.text-center.rounded-0.sticky-top
    = flash[:notice]
    button.btn-close.float-end type="button" data-bs-dismiss="alert"

- if alert
  .alert.alert-danger.text-center.rounded-0.sticky-top
    = flash[:alert]
    button.btn-close.float-end type="button" data-bs-dismiss="alert"

app/views/layouts/_head.html.slim
title = content_for(:title) || "Project Manger"
meta[name="viewport" content="width=device-width,initial-scale=1"]
meta[name="apple-mobile-web-app-capable" content="yes"]
meta[name="mobile-web-app-capable" content="yes"]
= csrf_meta_tags
= csp_meta_tag

= yield :head

link[rel="icon" href="/icon.png" type="image/png"]
link[rel="icon" href="/icon.svg" type="image/svg+xml"]
link[rel="apple-touch-icon" href="/icon.png"]

= stylesheet_link_tag :app, "data-turbo-track": "reload"
= javascript_importmap_tags
= stylesheet_link_tag "application", "data-turbo-track": "reload"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.bg-body-tertiary
  .container
    = link_to "Project Manager", root_path, class: "navbar-brand"

    button.navbar-toggler.ms-auto [
      type="button" data-bs-toggle="collapse"
      data-bs-target="#collapseNavbar"]
      span.navbar-toggler-icon
    .navbar-collapse.collapse#collapseNavbar
      ul.navbar-nav.ms-auto
        li.nav-item
          = button_to "Sign Out", destroy_user_session_path,
            class: "nav-link", method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    = render "layouts/head"

  body
    = render "layouts/navbar"
    = render "layouts/flash"
    .container
      = yield

app/views/layouts/authentication.html.slim
doctype html
html
  head
    = render "layouts/head"

  body
    .container
      = yield

app/views/projects/_entry.html.slim
= render "projects/entry/#{entry.entryable_name}", entry: entry

app/views/projects/_project.html.slim
tr[data-controller="redirect"
  data-action="click->redirect#perform"
  data-redirect-url-value=project_path(project)]
  td = project.id
  td = project
  td = t project.status, scope: "activerecord.attributes.project.statuses"
  td = l project.created_at, format: :short
  td = l project.updated_at, format: :short

app/views/projects/comments/new.html.slim
= turbo_frame_tag @project, :new_comment
  h4.my-3 New Comment

  = form_with model: [@project, @comment] do |f|
    .mb-3
      = f.label :text, class: "form-label"
      = f.text_area :text, class: "form-control"
      = error_on(f.object, :text)

    .row
      .col-auto
        = f.submit class: "btn btn-primary"
      .col
        = link_to "Cancel", project_path(@project), class: "btn btn-danger"

app/views/projects/entry/_comment.html.slim
.card.mt-3[id="#{dom_id(entry)}"]
  .card-header.d-flex
    = entry.user

    .ms-auto
      = l entry.created_at, format: :short
  .card-body
    = entry.comment

app/views/projects/entry/_project_status_change.html.slim
.card.mt-3[id="#{dom_id(entry)}"]
  .card-body
    | #{entry.user} changed status
    |  from: #{t entry.project_status_change.from, scope: "activerecord.attributes.project.statuses"}
    |  to: #{t entry.project_status_change.to, scope: "activerecord.attributes.project.statuses"}
    |  at #{l entry.created_at, format: :short}

app/views/projects/index.html.slim
.d-flex.my-5
  h1 Projects

  = link_to "Add new", new_project_path,
    class: "btn btn-lg btn-primary ms-auto align-self-center"

table.table.table-hover
  thead
    tr
      th #
      th Name
      th Status
      th Created At
      th Updated At
  tbody
    = render @projects

app/views/projects/new.html.slim
h1.my-5 New Project

= form_with model: @project do |f|
  .mb-3
    = f.label :name, class: "form-label"
    = f.text_field :name, class: "form-control"
    = error_on(f.object, :name)

  .mb-3
    = f.label :status, class: "form-label"
    = f.select :status, project_statuses, {}, class: "form-select"
    = error_on(f.object, :status)

  .mb-3
    = f.label :text, class: "form-label"
    = f.text_area :text, class: "form-control"
    = error_on(f.object, :text)

  .row
    .col-auto
      = f.submit class: "btn btn-primary"
    .col
      = link_to "Cancel", projects_path, class: "btn btn-danger"

app/views/projects/show.html.slim
= turbo_stream_from @project, "entries"

.my-5
  h1 = "#{@project} ##{@project.id}"

= turbo_frame_tag @project, :status
  h4.mt-3
    = link_to t(@project.status,
      scope: "activerecord.attributes.project.statuses"),
      new_project_status_change_path(@project),
      class: "badge text-decoration-none #{project_status_badge(@project)}"

p.my-5
  = @project.text

#entries
  = render partial: "projects/entry", collection: @entries

= turbo_frame_tag dom_id @project, :new_comment
  = link_to "Add a comment", new_project_comment_path(@project),
    class: "btn btn-primary mt-5"

app/views/projects/status_changes/new.html.slim
= turbo_frame_tag @project, :status
  = form_with url: project_status_changes_path(@project),
    data: { controller: "form-submit" } do |f|
    .row
      .col-auto
        = f.select :status, project_statuses, { selected: @project.status },
          class: "form-select", data: { action: "form-submit#submit" }
      .col
        = link_to "Cancel", project_path(@project), class: "btn btn-danger"